name: Build qa stable
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test --passWithNoTests
      - name: Build
        run: npm run build:qa --if-present
