name: Lint Test Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm ci
      - name: Test 
        run: npm test --passWithNoTests
      - name: Build 
        run: npm run build --if-present
      - name: Add Jenkins File 
        run: |
          cp ${{ github.workspace }}/JenkinsFile ${{ github.workspace }}/dist/58231b16fdee45a03a4ee3cf94a9f2c3
      # store the build files into the cache
      - name: Cache Build
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ${{ github.workspace }}/dist/*
          key: ${{ github.sha }}